name: pre-release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Unshallow
      run: git fetch --prune --unshallow
    -
      name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    -
      name: Build GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: build --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
